//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DateSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DateSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Year"/>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Month"/>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Day"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CalendarTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateSchemaType", propOrder = { "year", "month", "day" })
public class DateSchemaType {

    @XmlElement(name = "Year", required = true)
    protected Year                  year;
    @XmlElement(name = "Month", required = true)
    protected Month                 month;
    @XmlElement(name = "Day", required = true)
    protected Day                   day;
    @XmlAttribute(name = "CalendarTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger            calendarTypeID;
    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the calendarTypeID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getCalendarTypeID() {
        return calendarTypeID;
    }

    /**
     * Gets the value of the day property.
     *
     * @return possible object is {@link Day }
     */
    public Day getDay() {
        return day;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the month property.
     *
     * @return possible object is {@link Month }
     */
    public Month getMonth() {
        return month;
    }

    /**
     * Gets the value of the year property.
     *
     * @return possible object is {@link Year }
     */
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the calendarTypeID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setCalendarTypeID(final BigInteger value) {
        calendarTypeID = value;
    }

    /**
     * Sets the value of the day property.
     *
     * @param value
     *            allowed object is {@link Day }
     */
    public void setDay(final Day value) {
        day = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the month property.
     *
     * @param value
     *            allowed object is {@link Month }
     */
    public void setMonth(final Month value) {
        month = value;
    }

    /**
     * Sets the value of the year property.
     *
     * @param value
     *            allowed object is {@link Year }
     */
    public void setYear(final Year value) {
        year = value;
    }

}
