//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DateBoundarySchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DateBoundarySchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.un.org/sanctions/1.0}From"/>
 *           &lt;element ref="{http://www.un.org/sanctions/1.0}To" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}To"/>
 *       &lt;/choice>
 *       &lt;attribute name="Approximate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="YearFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MonthFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DayFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateBoundarySchemaType", propOrder = { "content" })
public class DateBoundarySchemaType {

    @XmlElementRefs({ @XmlElementRef(name = "From", namespace = "http://www.un.org/sanctions/1.0", type = JAXBElement.class),
            @XmlElementRef(name = "To", namespace = "http://www.un.org/sanctions/1.0", type = JAXBElement.class) })
    protected List<JAXBElement<DatePointSchemaType>> content;
    @XmlAttribute(name = "Approximate", required = true)
    protected boolean                                approximate;
    @XmlAttribute(name = "YearFixed", required = true)
    protected boolean                                yearFixed;
    @XmlAttribute(name = "MonthFixed", required = true)
    protected boolean                                monthFixed;
    @XmlAttribute(name = "DayFixed", required = true)
    protected boolean                                dayFixed;
    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType                  deltaAction;

    /**
     * Gets the rest of the content model.
     * <p>
     * You are getting this "catch-all" property because of the following reason: The field name "To" is used by two different parts of a schema. See: line 1228 of
     * file:/C:/Users/N970130/Documents/Workspace/SanctionList/ lists/ofac-sdn_advanced.xsd line 1226 of file:/C:/Users/N970130/Documents/ Workspace/SanctionList/lists/ofac-sdn_advanced.xsd
     * <p>
     * To get rid of this property, apply a property customization to one of both of the following declarations to change their names: Gets the value of the content property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the content property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link DatePointSchemaType }{@code >} {@link JAXBElement }{@code <}{@link DatePointSchemaType }{@code >}
     */
    public List<JAXBElement<DatePointSchemaType>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<DatePointSchemaType>>();
        }
        return content;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the approximate property.
     */
    public boolean isApproximate() {
        return approximate;
    }

    /**
     * Gets the value of the dayFixed property.
     */
    public boolean isDayFixed() {
        return dayFixed;
    }

    /**
     * Gets the value of the monthFixed property.
     */
    public boolean isMonthFixed() {
        return monthFixed;
    }

    /**
     * Gets the value of the yearFixed property.
     */
    public boolean isYearFixed() {
        return yearFixed;
    }

    /**
     * Sets the value of the approximate property.
     */
    public void setApproximate(final boolean value) {
        approximate = value;
    }

    /**
     * Sets the value of the dayFixed property.
     */
    public void setDayFixed(final boolean value) {
        dayFixed = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the monthFixed property.
     */
    public void setMonthFixed(final boolean value) {
        monthFixed = value;
    }

    /**
     * Sets the value of the yearFixed property.
     */
    public void setYearFixed(final boolean value) {
        yearFixed = value;
    }

}
