//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DeltaActionSchemaType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="DeltaActionSchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="add"/>
 *     &lt;enumeration value="amend"/>
 *     &lt;enumeration value="delete"/>
 *     &lt;enumeration value="revise"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "DeltaActionSchemaType")
@XmlEnum
public enum DeltaActionSchemaType {

    @XmlEnumValue("add") ADD("add"), @XmlEnumValue("amend") AMEND("amend"), @XmlEnumValue("delete") DELETE("delete"), @XmlEnumValue("revise") REVISE("revise");
    public static DeltaActionSchemaType fromValue(final String v) {
        for (final DeltaActionSchemaType c : DeltaActionSchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    private final String value;

    DeltaActionSchemaType(final String v) {
        value = v;
    }

    public String value() {
        return value;
    }

}
