//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for DistinctPartySchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DistinctPartySchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Profile" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Identity" type="{http://www.un.org/sanctions/1.0}IdentitySchemaType" maxOccurs="unbounded"/>
 *                   &lt;element name="Feature" type="{http://www.un.org/sanctions/1.0}FeatureSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="SanctionsEntryReference" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                             &lt;element name="ExRefValue" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL" minOccurs="0"/>
 *                             &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Description" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                     &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="PartySubTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="FixedRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistinctPartySchemaType", propOrder = { "comment", "profile" })
public class DistinctPartySchemaType {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Identity" type="{http://www.un.org/sanctions/1.0}IdentitySchemaType" maxOccurs="unbounded"/>
     *         &lt;element name="Feature" type="{http://www.un.org/sanctions/1.0}FeatureSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="SanctionsEntryReference" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *                   &lt;element name="ExRefValue" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL" minOccurs="0"/>
     *                   &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Description" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="PartySubTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment", "identity", "feature", "sanctionsEntryReference", "externalReference" })
    public static class Profile {

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
         *         &lt;element name="ExRefValue" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL" minOccurs="0"/>
         *         &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Description" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "comment", "exRefValue", "directURL", "subLink" })
        public static class ExternalReference {

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class ExRefValue {

                @XmlValue
                protected String                value;
                @XmlAttribute(name = "DeltaAction")
                protected DeltaActionSchemaType deltaAction;

                /**
                 * Gets the value of the deltaAction property.
                 *
                 * @return possible object is {@link DeltaActionSchemaType }
                 */
                public DeltaActionSchemaType getDeltaAction() {
                    return deltaAction;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the deltaAction property.
                 *
                 * @param value
                 *            allowed object is {@link DeltaActionSchemaType }
                 */
                public void setDeltaAction(final DeltaActionSchemaType value) {
                    deltaAction = value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *            allowed object is {@link String }
                 */
                public void setValue(final String value) {
                    this.value = value;
                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Description" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL"/>
             *       &lt;/sequence>
             *       &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "description", "directURL" })
            public static class SubLink {

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 * <p>
                 * The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "value" })
                public static class Description {

                    @XmlValue
                    protected String                value;
                    @XmlAttribute(name = "DeltaAction")
                    protected DeltaActionSchemaType deltaAction;

                    /**
                     * Gets the value of the deltaAction property.
                     *
                     * @return possible object is {@link DeltaActionSchemaType }
                     */
                    public DeltaActionSchemaType getDeltaAction() {
                        return deltaAction;
                    }

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the deltaAction property.
                     *
                     * @param value
                     *            allowed object is {@link DeltaActionSchemaType }
                     */
                    public void setDeltaAction(final DeltaActionSchemaType value) {
                        deltaAction = value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value
                     *            allowed object is {@link String }
                     */
                    public void setValue(final String value) {
                        this.value = value;
                    }

                }

                @XmlElement(name = "Description")
                protected DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description description;
                @XmlElement(name = "DirectURL", required = true)
                protected DirectURL                                                             directURL;
                @XmlAttribute(name = "TargetTypeID", required = true)
                @XmlSchemaType(name = "nonNegativeInteger")
                protected BigInteger                                                            targetTypeID;

                @XmlAttribute(name = "DeltaAction")
                protected DeltaActionSchemaType                                                 deltaAction;

                /**
                 * Gets the value of the deltaAction property.
                 *
                 * @return possible object is {@link DeltaActionSchemaType }
                 */
                public DeltaActionSchemaType getDeltaAction() {
                    return deltaAction;
                }

                /**
                 * Gets the value of the description property.
                 *
                 * @return possible object is {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description }
                 */
                public DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description getDescription() {
                    return description;
                }

                /**
                 * Gets the value of the directURL property.
                 *
                 * @return possible object is {@link DirectURL }
                 */
                public DirectURL getDirectURL() {
                    return directURL;
                }

                /**
                 * Gets the value of the targetTypeID property.
                 *
                 * @return possible object is {@link BigInteger }
                 */
                public BigInteger getTargetTypeID() {
                    return targetTypeID;
                }

                /**
                 * Sets the value of the deltaAction property.
                 *
                 * @param value
                 *            allowed object is {@link DeltaActionSchemaType }
                 */
                public void setDeltaAction(final DeltaActionSchemaType value) {
                    deltaAction = value;
                }

                /**
                 * Sets the value of the description property.
                 *
                 * @param value
                 *            allowed object is {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description }
                 */
                public void setDescription(final DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description value) {
                    description = value;
                }

                /**
                 * Sets the value of the directURL property.
                 *
                 * @param value
                 *            allowed object is {@link DirectURL }
                 */
                public void setDirectURL(final DirectURL value) {
                    directURL = value;
                }

                /**
                 * Sets the value of the targetTypeID property.
                 *
                 * @param value
                 *            allowed object is {@link BigInteger }
                 */
                public void setTargetTypeID(final BigInteger value) {
                    targetTypeID = value;
                }

            }

            @XmlElement(name = "Comment")
            protected Comment                                                         comment;
            @XmlElement(name = "ExRefValue")
            protected DistinctPartySchemaType.Profile.ExternalReference.ExRefValue    exRefValue;
            @XmlElement(name = "DirectURL")
            protected DirectURL                                                       directURL;
            @XmlElement(name = "SubLink")
            protected List<DistinctPartySchemaType.Profile.ExternalReference.SubLink> subLink;

            @XmlAttribute(name = "ExRefTypeID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger                                                      exRefTypeID;

            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType                                           deltaAction;

            /**
             * Gets the value of the comment property.
             *
             * @return possible object is {@link Comment }
             */
            public Comment getComment() {
                return comment;
            }

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the directURL property.
             *
             * @return possible object is {@link DirectURL }
             */
            public DirectURL getDirectURL() {
                return directURL;
            }

            /**
             * Gets the value of the exRefTypeID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getExRefTypeID() {
                return exRefTypeID;
            }

            /**
             * Gets the value of the exRefValue property.
             *
             * @return possible object is {@link DistinctPartySchemaType.Profile.ExternalReference.ExRefValue }
             */
            public DistinctPartySchemaType.Profile.ExternalReference.ExRefValue getExRefValue() {
                return exRefValue;
            }

            /**
             * Gets the value of the subLink property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why
             * there is not a <CODE>set</CODE> method for the subLink property.
             * <p>
             * For example, to add a new item, do as follows:
             *
             * <pre>
             * getSubLink().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink }
             */
            public List<DistinctPartySchemaType.Profile.ExternalReference.SubLink> getSubLink() {
                if (subLink == null) {
                    subLink = new ArrayList<DistinctPartySchemaType.Profile.ExternalReference.SubLink>();
                }
                return subLink;
            }

            /**
             * Sets the value of the comment property.
             *
             * @param value
             *            allowed object is {@link Comment }
             */
            public void setComment(final Comment value) {
                comment = value;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the directURL property.
             *
             * @param value
             *            allowed object is {@link DirectURL }
             */
            public void setDirectURL(final DirectURL value) {
                directURL = value;
            }

            /**
             * Sets the value of the exRefTypeID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setExRefTypeID(final BigInteger value) {
                exRefTypeID = value;
            }

            /**
             * Sets the value of the exRefValue property.
             *
             * @param value
             *            allowed object is {@link DistinctPartySchemaType.Profile.ExternalReference.ExRefValue }
             */
            public void setExRefValue(final DistinctPartySchemaType.Profile.ExternalReference.ExRefValue value) {
                exRefValue = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SanctionsEntryReference {

            @XmlAttribute(name = "SanctionsEntryID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            sanctionsEntryID;
            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the sanctionsEntryID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getSanctionsEntryID() {
                return sanctionsEntryID;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the sanctionsEntryID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setSanctionsEntryID(final BigInteger value) {
                sanctionsEntryID = value;
            }

        }

        @XmlElement(name = "Comment")
        protected List<Comment>                                                 comment;
        @XmlElement(name = "Identity", required = true)
        protected List<IdentitySchemaType>                                      identity;
        @XmlElement(name = "Feature")
        protected List<FeatureSchemaType>                                       feature;
        @XmlElement(name = "SanctionsEntryReference")
        protected List<DistinctPartySchemaType.Profile.SanctionsEntryReference> sanctionsEntryReference;
        @XmlElement(name = "ExternalReference")
        protected List<DistinctPartySchemaType.Profile.ExternalReference>       externalReference;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                                    id;

        @XmlAttribute(name = "PartySubTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                                    partySubTypeID;

        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType                                         deltaAction;

        /**
         * Gets the value of the comment property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the comment property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getComment().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link Comment }
         */
        public List<Comment> getComment() {
            if (comment == null) {
                comment = new ArrayList<Comment>();
            }
            return comment;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the externalReference property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the externalReference property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getExternalReference().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DistinctPartySchemaType.Profile.ExternalReference }
         */
        public List<DistinctPartySchemaType.Profile.ExternalReference> getExternalReference() {
            if (externalReference == null) {
                externalReference = new ArrayList<DistinctPartySchemaType.Profile.ExternalReference>();
            }
            return externalReference;
        }

        /**
         * Gets the value of the feature property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the feature property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getFeature().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link FeatureSchemaType }
         */
        public List<FeatureSchemaType> getFeature() {
            if (feature == null) {
                feature = new ArrayList<FeatureSchemaType>();
            }
            return feature;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Gets the value of the identity property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the identity property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getIdentity().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link IdentitySchemaType }
         */
        public List<IdentitySchemaType> getIdentity() {
            if (identity == null) {
                identity = new ArrayList<IdentitySchemaType>();
            }
            return identity;
        }

        /**
         * Gets the value of the partySubTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getPartySubTypeID() {
            return partySubTypeID;
        }

        /**
         * Gets the value of the sanctionsEntryReference property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the sanctionsEntryReference property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getSanctionsEntryReference().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DistinctPartySchemaType.Profile.SanctionsEntryReference }
         */
        public List<DistinctPartySchemaType.Profile.SanctionsEntryReference> getSanctionsEntryReference() {
            if (sanctionsEntryReference == null) {
                sanctionsEntryReference = new ArrayList<DistinctPartySchemaType.Profile.SanctionsEntryReference>();
            }
            return sanctionsEntryReference;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setID(final BigInteger value) {
            id = value;
        }

        /**
         * Sets the value of the partySubTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setPartySubTypeID(final BigInteger value) {
            partySubTypeID = value;
        }

    }

    @XmlElement(name = "Comment")
    protected List<Comment>                         comment;
    @XmlElement(name = "Profile", required = true)
    protected List<DistinctPartySchemaType.Profile> profile;
    @XmlAttribute(name = "FixedRef", required = true)
    protected String                                fixedRef;

    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType                 deltaAction;

    /**
     * Gets the value of the comment property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the comment property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getComment().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Comment }
     */
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return comment;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the fixedRef property.
     *
     * @return possible object is {@link String }
     */
    public String getFixedRef() {
        return fixedRef;
    }

    /**
     * Gets the value of the profile property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the profile property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getProfile().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DistinctPartySchemaType.Profile }
     */
    public List<DistinctPartySchemaType.Profile> getProfile() {
        if (profile == null) {
            profile = new ArrayList<DistinctPartySchemaType.Profile>();
        }
        return profile;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the fixedRef property.
     *
     * @param value
     *            allowed object is {@link String }
     */
    public void setFixedRef(final String value) {
        fixedRef = value;
    }

}
