//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for DocumentedNameSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentedNameSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *         &lt;element name="DocumentedNamePart" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NamePartValue">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="NamePartGroupID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="ScriptID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="ScriptStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="Acronym" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LeadingChars" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TrailingChars" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DocumentedNameCountry" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="CountryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}IDRegDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="FixedRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DocNameStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentedNameSchemaType", propOrder = { "comment", "documentedNamePart", "documentedNameCountry", "idRegDocumentReference" })
public class DocumentedNameSchemaType {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="CountryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment" })
    public static class DocumentedNameCountry {

        @XmlElement(name = "Comment")
        protected Comment               comment;
        @XmlAttribute(name = "CountryID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            countryID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the comment property.
         *
         * @return possible object is {@link Comment }
         */
        public Comment getComment() {
            return comment;
        }

        /**
         * Gets the value of the countryID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getCountryID() {
            return countryID;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *            allowed object is {@link Comment }
         */
        public void setComment(final Comment value) {
            comment = value;
        }

        /**
         * Sets the value of the countryID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setCountryID(final BigInteger value) {
            countryID = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NamePartValue">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="NamePartGroupID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="ScriptID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="ScriptStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="Acronym" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LeadingChars" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TrailingChars" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "namePartValue" })
    public static class DocumentedNamePart {

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="NamePartGroupID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="ScriptID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="ScriptStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="Acronym" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "value" })
        public static class NamePartValue {

            @XmlValue
            protected String                value;
            @XmlAttribute(name = "NamePartGroupID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            namePartGroupID;
            @XmlAttribute(name = "ScriptID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            scriptID;
            @XmlAttribute(name = "ScriptStatusID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            scriptStatusID;
            @XmlAttribute(name = "Acronym", required = true)
            protected boolean               acronym;
            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the namePartGroupID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getNamePartGroupID() {
                return namePartGroupID;
            }

            /**
             * Gets the value of the scriptID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getScriptID() {
                return scriptID;
            }

            /**
             * Gets the value of the scriptStatusID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getScriptStatusID() {
                return scriptStatusID;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link String }
             */
            public String getValue() {
                return value;
            }

            /**
             * Gets the value of the acronym property.
             */
            public boolean isAcronym() {
                return acronym;
            }

            /**
             * Sets the value of the acronym property.
             */
            public void setAcronym(final boolean value) {
                acronym = value;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the namePartGroupID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setNamePartGroupID(final BigInteger value) {
                namePartGroupID = value;
            }

            /**
             * Sets the value of the scriptID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setScriptID(final BigInteger value) {
                scriptID = value;
            }

            /**
             * Sets the value of the scriptStatusID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setScriptStatusID(final BigInteger value) {
                scriptStatusID = value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *            allowed object is {@link String }
             */
            public void setValue(final String value) {
                this.value = value;
            }

        }

        @XmlElement(name = "NamePartValue", required = true)
        protected DocumentedNameSchemaType.DocumentedNamePart.NamePartValue namePartValue;
        @XmlAttribute(name = "LeadingChars")
        protected String                                                    leadingChars;
        @XmlAttribute(name = "TrailingChars")
        protected String                                                    trailingChars;

        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType                                     deltaAction;

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the leadingChars property.
         *
         * @return possible object is {@link String }
         */
        public String getLeadingChars() {
            return leadingChars;
        }

        /**
         * Gets the value of the namePartValue property.
         *
         * @return possible object is {@link DocumentedNameSchemaType.DocumentedNamePart.NamePartValue }
         */
        public DocumentedNameSchemaType.DocumentedNamePart.NamePartValue getNamePartValue() {
            return namePartValue;
        }

        /**
         * Gets the value of the trailingChars property.
         *
         * @return possible object is {@link String }
         */
        public String getTrailingChars() {
            return trailingChars;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the leadingChars property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setLeadingChars(final String value) {
            leadingChars = value;
        }

        /**
         * Sets the value of the namePartValue property.
         *
         * @param value
         *            allowed object is {@link DocumentedNameSchemaType.DocumentedNamePart.NamePartValue }
         */
        public void setNamePartValue(final DocumentedNameSchemaType.DocumentedNamePart.NamePartValue value) {
            namePartValue = value;
        }

        /**
         * Sets the value of the trailingChars property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setTrailingChars(final String value) {
            trailingChars = value;
        }

    }

    @XmlElement(name = "Comment")
    protected Comment                                              comment;
    @XmlElement(name = "DocumentedNamePart", required = true)
    protected List<DocumentedNameSchemaType.DocumentedNamePart>    documentedNamePart;
    @XmlElement(name = "DocumentedNameCountry")
    protected List<DocumentedNameSchemaType.DocumentedNameCountry> documentedNameCountry;
    @XmlElement(name = "IDRegDocumentReference")
    protected List<IDRegDocumentReference>                         idRegDocumentReference;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                                           id;
    @XmlAttribute(name = "FixedRef", required = true)
    protected String                                               fixedRef;

    @XmlAttribute(name = "DocNameStatusID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                                           docNameStatusID;

    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType                                deltaAction;

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is {@link Comment }
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the docNameStatusID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getDocNameStatusID() {
        return docNameStatusID;
    }

    /**
     * Gets the value of the documentedNameCountry property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the documentedNameCountry property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDocumentedNameCountry().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DocumentedNameSchemaType.DocumentedNameCountry }
     */
    public List<DocumentedNameSchemaType.DocumentedNameCountry> getDocumentedNameCountry() {
        if (documentedNameCountry == null) {
            documentedNameCountry = new ArrayList<DocumentedNameSchemaType.DocumentedNameCountry>();
        }
        return documentedNameCountry;
    }

    /**
     * Gets the value of the documentedNamePart property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the documentedNamePart property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDocumentedNamePart().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DocumentedNameSchemaType.DocumentedNamePart }
     */
    public List<DocumentedNameSchemaType.DocumentedNamePart> getDocumentedNamePart() {
        if (documentedNamePart == null) {
            documentedNamePart = new ArrayList<DocumentedNameSchemaType.DocumentedNamePart>();
        }
        return documentedNamePart;
    }

    /**
     * Gets the value of the fixedRef property.
     *
     * @return possible object is {@link String }
     */
    public String getFixedRef() {
        return fixedRef;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Gets the value of the idRegDocumentReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the idRegDocumentReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIDRegDocumentReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IDRegDocumentReference }
     */
    public List<IDRegDocumentReference> getIDRegDocumentReference() {
        if (idRegDocumentReference == null) {
            idRegDocumentReference = new ArrayList<IDRegDocumentReference>();
        }
        return idRegDocumentReference;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *            allowed object is {@link Comment }
     */
    public void setComment(final Comment value) {
        comment = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the docNameStatusID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setDocNameStatusID(final BigInteger value) {
        docNameStatusID = value;
    }

    /**
     * Sets the value of the fixedRef property.
     *
     * @param value
     *            allowed object is {@link String }
     */
    public void setFixedRef(final String value) {
        fixedRef = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

}
