//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EntryDeltaFlagSchemaType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="EntryDeltaFlagSchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NewEntry"/>
 *     &lt;enumeration value="DeletedEntry"/>
 *     &lt;enumeration value="ModifiedEntry"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "EntryDeltaFlagSchemaType")
@XmlEnum
public enum EntryDeltaFlagSchemaType {

    @XmlEnumValue("NewEntry") NEW_ENTRY("NewEntry"), @XmlEnumValue("DeletedEntry") DELETED_ENTRY("DeletedEntry"), @XmlEnumValue("ModifiedEntry") MODIFIED_ENTRY("ModifiedEntry");
    public static EntryDeltaFlagSchemaType fromValue(final String v) {
        for (final EntryDeltaFlagSchemaType c : EntryDeltaFlagSchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    private final String value;

    EntryDeltaFlagSchemaType(final String v) {
        value = v;
    }

    public String value() {
        return value;
    }

}
