//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for FeatureSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FeatureSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureVersion" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}DatePeriod" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="VersionDetail" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="DetailTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DetailReferenceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="VersionLocation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="LocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}IDRegDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="ReliabilityID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IdentityReference" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="IdentityID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="IdentityFeatureLinkTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="FeatureTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureSchemaType", propOrder = { "featureVersion", "identityReference" })
public class FeatureSchemaType {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}DatePeriod" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="VersionDetail" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="DetailTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DetailReferenceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="VersionLocation" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="LocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}IDRegDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="ReliabilityID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment", "datePeriod", "versionDetail", "versionLocation", "idRegDocumentReference" })
    public static class FeatureVersion {

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="DetailTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DetailReferenceID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "value" })
        public static class VersionDetail {

            @XmlValue
            protected String                value;
            @XmlAttribute(name = "DetailTypeID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            detailTypeID;
            @XmlAttribute(name = "DetailReferenceID")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            detailReferenceID;
            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the detailReferenceID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getDetailReferenceID() {
                return detailReferenceID;
            }

            /**
             * Gets the value of the detailTypeID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getDetailTypeID() {
                return detailTypeID;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link String }
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the detailReferenceID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setDetailReferenceID(final BigInteger value) {
                detailReferenceID = value;
            }

            /**
             * Sets the value of the detailTypeID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setDetailTypeID(final BigInteger value) {
                detailTypeID = value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *            allowed object is {@link String }
             */
            public void setValue(final String value) {
                this.value = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="LocationID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VersionLocation {

            @XmlAttribute(name = "LocationID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger            locationID;
            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the locationID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getLocationID() {
                return locationID;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the locationID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setLocationID(final BigInteger value) {
                locationID = value;
            }

        }

        @XmlElement(name = "Comment")
        protected Comment                                                comment;
        @XmlElement(name = "DatePeriod")
        protected List<DatePeriod>                                       datePeriod;
        @XmlElement(name = "VersionDetail")
        protected List<FeatureSchemaType.FeatureVersion.VersionDetail>   versionDetail;
        @XmlElement(name = "VersionLocation")
        protected List<FeatureSchemaType.FeatureVersion.VersionLocation> versionLocation;
        @XmlElement(name = "IDRegDocumentReference")
        protected List<IDRegDocumentReference>                           idRegDocumentReference;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                             id;

        @XmlAttribute(name = "ReliabilityID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger reliabilityID;

        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the comment property.
         *
         * @return possible object is {@link Comment }
         */
        public Comment getComment() {
            return comment;
        }

        /**
         * Gets the value of the datePeriod property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the datePeriod property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getDatePeriod().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DatePeriod }
         */
        public List<DatePeriod> getDatePeriod() {
            if (datePeriod == null) {
                datePeriod = new ArrayList<DatePeriod>();
            }
            return datePeriod;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Gets the value of the idRegDocumentReference property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the idRegDocumentReference property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getIDRegDocumentReference().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link IDRegDocumentReference }
         */
        public List<IDRegDocumentReference> getIDRegDocumentReference() {
            if (idRegDocumentReference == null) {
                idRegDocumentReference = new ArrayList<IDRegDocumentReference>();
            }
            return idRegDocumentReference;
        }

        /**
         * Gets the value of the reliabilityID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getReliabilityID() {
            return reliabilityID;
        }

        /**
         * Gets the value of the versionDetail property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the versionDetail property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getVersionDetail().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link FeatureSchemaType.FeatureVersion.VersionDetail }
         */
        public List<FeatureSchemaType.FeatureVersion.VersionDetail> getVersionDetail() {
            if (versionDetail == null) {
                versionDetail = new ArrayList<FeatureSchemaType.FeatureVersion.VersionDetail>();
            }
            return versionDetail;
        }

        /**
         * Gets the value of the versionLocation property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the versionLocation property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getVersionLocation().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link FeatureSchemaType.FeatureVersion.VersionLocation }
         */
        public List<FeatureSchemaType.FeatureVersion.VersionLocation> getVersionLocation() {
            if (versionLocation == null) {
                versionLocation = new ArrayList<FeatureSchemaType.FeatureVersion.VersionLocation>();
            }
            return versionLocation;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *            allowed object is {@link Comment }
         */
        public void setComment(final Comment value) {
            comment = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setID(final BigInteger value) {
            id = value;
        }

        /**
         * Sets the value of the reliabilityID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setReliabilityID(final BigInteger value) {
            reliabilityID = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="IdentityID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="IdentityFeatureLinkTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IdentityReference {

        @XmlAttribute(name = "IdentityID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            identityID;
        @XmlAttribute(name = "IdentityFeatureLinkTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            identityFeatureLinkTypeID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the identityFeatureLinkTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getIdentityFeatureLinkTypeID() {
            return identityFeatureLinkTypeID;
        }

        /**
         * Gets the value of the identityID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getIdentityID() {
            return identityID;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the identityFeatureLinkTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setIdentityFeatureLinkTypeID(final BigInteger value) {
            identityFeatureLinkTypeID = value;
        }

        /**
         * Sets the value of the identityID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setIdentityID(final BigInteger value) {
            identityID = value;
        }

    }

    @XmlElement(name = "FeatureVersion", required = true)
    protected List<FeatureSchemaType.FeatureVersion>    featureVersion;
    @XmlElement(name = "IdentityReference", required = true)
    protected List<FeatureSchemaType.IdentityReference> identityReference;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                                id;

    @XmlAttribute(name = "FeatureTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger featureTypeID;

    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the featureTypeID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getFeatureTypeID() {
        return featureTypeID;
    }

    /**
     * Gets the value of the featureVersion property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the featureVersion property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getFeatureVersion().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link FeatureSchemaType.FeatureVersion }
     */
    public List<FeatureSchemaType.FeatureVersion> getFeatureVersion() {
        if (featureVersion == null) {
            featureVersion = new ArrayList<FeatureSchemaType.FeatureVersion>();
        }
        return featureVersion;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Gets the value of the identityReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the identityReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIdentityReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link FeatureSchemaType.IdentityReference }
     */
    public List<FeatureSchemaType.IdentityReference> getIdentityReference() {
        if (identityReference == null) {
            identityReference = new ArrayList<FeatureSchemaType.IdentityReference>();
        }
        return identityReference;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the featureTypeID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setFeatureTypeID(final BigInteger value) {
        featureTypeID = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

}
