//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for LocationSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LocationSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *         &lt;element name="LocationAreaCode" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="AreaCodeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LocationCountry" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CountryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="CountryRelevanceID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LocationPart" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LocationPartValue" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                             &lt;element name="Value">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Primary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="LocPartValueTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="LocPartValueStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocPartTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}FeatureVersionReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}IDRegDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationSchemaType", propOrder = { "comment", "locationAreaCode", "locationCountry", "locationPart", "featureVersionReference", "idRegDocumentReference" })
public class LocationSchemaType {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="AreaCodeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LocationAreaCode {

        @XmlAttribute(name = "AreaCodeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            areaCodeID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the areaCodeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getAreaCodeID() {
            return areaCodeID;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Sets the value of the areaCodeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setAreaCodeID(final BigInteger value) {
            areaCodeID = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CountryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="CountryRelevanceID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LocationCountry {

        @XmlAttribute(name = "CountryID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            countryID;
        @XmlAttribute(name = "CountryRelevanceID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            countryRelevanceID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the countryID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getCountryID() {
            return countryID;
        }

        /**
         * Gets the value of the countryRelevanceID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getCountryRelevanceID() {
            return countryRelevanceID;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Sets the value of the countryID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setCountryID(final BigInteger value) {
            countryID = value;
        }

        /**
         * Sets the value of the countryRelevanceID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setCountryRelevanceID(final BigInteger value) {
            countryRelevanceID = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LocationPartValue" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *                   &lt;element name="Value">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Primary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="LocPartValueTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="LocPartValueStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocPartTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "locationPartValue" })
    public static class LocationPart {

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
         *         &lt;element name="Value">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Primary" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="LocPartValueTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="LocPartValueStatusID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "comment", "value" })
        public static class LocationPartValue {

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class Value {

                @XmlValue
                protected String                value;
                @XmlAttribute(name = "DeltaAction")
                protected DeltaActionSchemaType deltaAction;

                /**
                 * Gets the value of the deltaAction property.
                 *
                 * @return possible object is {@link DeltaActionSchemaType }
                 */
                public DeltaActionSchemaType getDeltaAction() {
                    return deltaAction;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the deltaAction property.
                 *
                 * @param value
                 *            allowed object is {@link DeltaActionSchemaType }
                 */
                public void setDeltaAction(final DeltaActionSchemaType value) {
                    deltaAction = value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value
                 *            allowed object is {@link String }
                 */
                public void setValue(final String value) {
                    this.value = value;
                }

            }

            @XmlElement(name = "Comment")
            protected Comment                                                 comment;
            @XmlElement(name = "Value", required = true)
            protected LocationSchemaType.LocationPart.LocationPartValue.Value value;
            @XmlAttribute(name = "Primary", required = true)
            protected boolean                                                 primary;
            @XmlAttribute(name = "LocPartValueTypeID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger                                              locPartValueTypeID;
            @XmlAttribute(name = "LocPartValueStatusID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger                                              locPartValueStatusID;

            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the comment property.
             *
             * @return possible object is {@link Comment }
             */
            public Comment getComment() {
                return comment;
            }

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the locPartValueStatusID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getLocPartValueStatusID() {
                return locPartValueStatusID;
            }

            /**
             * Gets the value of the locPartValueTypeID property.
             *
             * @return possible object is {@link BigInteger }
             */
            public BigInteger getLocPartValueTypeID() {
                return locPartValueTypeID;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link LocationSchemaType.LocationPart.LocationPartValue.Value }
             */
            public LocationSchemaType.LocationPart.LocationPartValue.Value getValue() {
                return value;
            }

            /**
             * Gets the value of the primary property.
             */
            public boolean isPrimary() {
                return primary;
            }

            /**
             * Sets the value of the comment property.
             *
             * @param value
             *            allowed object is {@link Comment }
             */
            public void setComment(final Comment value) {
                comment = value;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the locPartValueStatusID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setLocPartValueStatusID(final BigInteger value) {
                locPartValueStatusID = value;
            }

            /**
             * Sets the value of the locPartValueTypeID property.
             *
             * @param value
             *            allowed object is {@link BigInteger }
             */
            public void setLocPartValueTypeID(final BigInteger value) {
                locPartValueTypeID = value;
            }

            /**
             * Sets the value of the primary property.
             */
            public void setPrimary(final boolean value) {
                primary = value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *            allowed object is {@link LocationSchemaType.LocationPart.LocationPartValue.Value }
             */
            public void setValue(final LocationSchemaType.LocationPart.LocationPartValue.Value value) {
                this.value = value;
            }

        }

        @XmlElement(name = "LocationPartValue", required = true)
        protected List<LocationSchemaType.LocationPart.LocationPartValue> locationPartValue;
        @XmlAttribute(name = "LocPartTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                              locPartTypeID;

        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the locationPartValue property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the locationPartValue property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getLocationPartValue().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link LocationSchemaType.LocationPart.LocationPartValue }
         */
        public List<LocationSchemaType.LocationPart.LocationPartValue> getLocationPartValue() {
            if (locationPartValue == null) {
                locationPartValue = new ArrayList<LocationSchemaType.LocationPart.LocationPartValue>();
            }
            return locationPartValue;
        }

        /**
         * Gets the value of the locPartTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getLocPartTypeID() {
            return locPartTypeID;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the locPartTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setLocPartTypeID(final BigInteger value) {
            locPartTypeID = value;
        }

    }

    @XmlElement(name = "Comment")
    protected Comment                                   comment;
    @XmlElement(name = "LocationAreaCode")
    protected List<LocationSchemaType.LocationAreaCode> locationAreaCode;
    @XmlElement(name = "LocationCountry")
    protected List<LocationSchemaType.LocationCountry>  locationCountry;
    @XmlElement(name = "LocationPart")
    protected List<LocationSchemaType.LocationPart>     locationPart;
    @XmlElement(name = "FeatureVersionReference")
    protected List<FeatureVersionReference>             featureVersionReference;

    @XmlElement(name = "IDRegDocumentReference")
    protected List<IDRegDocumentReference> idRegDocumentReference;

    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;

    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is {@link Comment }
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the featureVersionReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the featureVersionReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getFeatureVersionReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link FeatureVersionReference }
     */
    public List<FeatureVersionReference> getFeatureVersionReference() {
        if (featureVersionReference == null) {
            featureVersionReference = new ArrayList<FeatureVersionReference>();
        }
        return featureVersionReference;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Gets the value of the idRegDocumentReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the idRegDocumentReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIDRegDocumentReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IDRegDocumentReference }
     */
    public List<IDRegDocumentReference> getIDRegDocumentReference() {
        if (idRegDocumentReference == null) {
            idRegDocumentReference = new ArrayList<IDRegDocumentReference>();
        }
        return idRegDocumentReference;
    }

    /**
     * Gets the value of the locationAreaCode property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the locationAreaCode property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getLocationAreaCode().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link LocationSchemaType.LocationAreaCode }
     */
    public List<LocationSchemaType.LocationAreaCode> getLocationAreaCode() {
        if (locationAreaCode == null) {
            locationAreaCode = new ArrayList<LocationSchemaType.LocationAreaCode>();
        }
        return locationAreaCode;
    }

    /**
     * Gets the value of the locationCountry property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the locationCountry property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getLocationCountry().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link LocationSchemaType.LocationCountry }
     */
    public List<LocationSchemaType.LocationCountry> getLocationCountry() {
        if (locationCountry == null) {
            locationCountry = new ArrayList<LocationSchemaType.LocationCountry>();
        }
        return locationCountry;
    }

    /**
     * Gets the value of the locationPart property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the locationPart property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getLocationPart().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link LocationSchemaType.LocationPart }
     */
    public List<LocationSchemaType.LocationPart> getLocationPart() {
        if (locationPart == null) {
            locationPart = new ArrayList<LocationSchemaType.LocationPart>();
        }
        return locationPart;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *            allowed object is {@link Comment }
     */
    public void setComment(final Comment value) {
        comment = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

}
