//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.un.org/sanctions/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package at.jps.sanction.core.list.ofac.ASDM;
