//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ProfileRelationshipSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProfileRelationshipSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}DatePeriod" minOccurs="0"/>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}IDRegDocumentReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="From-ProfileID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="To-ProfileID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="RelationTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="RelationQualityID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="Former" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfileRelationshipSchemaType", propOrder = { "comment", "datePeriod", "idRegDocumentReference" })
public class ProfileRelationshipSchemaType {

    @XmlElement(name = "Comment")
    protected Comment                      comment;
    @XmlElement(name = "DatePeriod")
    protected DatePeriod                   datePeriod;
    @XmlElement(name = "IDRegDocumentReference")
    protected List<IDRegDocumentReference> idRegDocumentReference;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   id;
    @XmlAttribute(name = "From-ProfileID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   fromProfileID;
    @XmlAttribute(name = "To-ProfileID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   toProfileID;
    @XmlAttribute(name = "RelationTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   relationTypeID;
    @XmlAttribute(name = "RelationQualityID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   relationQualityID;
    @XmlAttribute(name = "Former", required = true)
    protected boolean                      former;
    @XmlAttribute(name = "SanctionsEntryID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                   sanctionsEntryID;
    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType        deltaAction;

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is {@link Comment }
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Gets the value of the datePeriod property.
     *
     * @return possible object is {@link DatePeriod }
     */
    public DatePeriod getDatePeriod() {
        return datePeriod;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the fromProfileID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getFromProfileID() {
        return fromProfileID;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Gets the value of the idRegDocumentReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the idRegDocumentReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIDRegDocumentReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IDRegDocumentReference }
     */
    public List<IDRegDocumentReference> getIDRegDocumentReference() {
        if (idRegDocumentReference == null) {
            idRegDocumentReference = new ArrayList<IDRegDocumentReference>();
        }
        return idRegDocumentReference;
    }

    /**
     * Gets the value of the relationQualityID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getRelationQualityID() {
        return relationQualityID;
    }

    /**
     * Gets the value of the relationTypeID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getRelationTypeID() {
        return relationTypeID;
    }

    /**
     * Gets the value of the sanctionsEntryID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getSanctionsEntryID() {
        return sanctionsEntryID;
    }

    /**
     * Gets the value of the toProfileID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getToProfileID() {
        return toProfileID;
    }

    /**
     * Gets the value of the former property.
     */
    public boolean isFormer() {
        return former;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *            allowed object is {@link Comment }
     */
    public void setComment(final Comment value) {
        comment = value;
    }

    /**
     * Sets the value of the datePeriod property.
     *
     * @param value
     *            allowed object is {@link DatePeriod }
     */
    public void setDatePeriod(final DatePeriod value) {
        datePeriod = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the former property.
     */
    public void setFormer(final boolean value) {
        former = value;
    }

    /**
     * Sets the value of the fromProfileID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setFromProfileID(final BigInteger value) {
        fromProfileID = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

    /**
     * Sets the value of the relationQualityID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setRelationQualityID(final BigInteger value) {
        relationQualityID = value;
    }

    /**
     * Sets the value of the relationTypeID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setRelationTypeID(final BigInteger value) {
        relationTypeID = value;
    }

    /**
     * Sets the value of the sanctionsEntryID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setSanctionsEntryID(final BigInteger value) {
        sanctionsEntryID = value;
    }

    /**
     * Sets the value of the toProfileID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setToProfileID(final BigInteger value) {
        toProfileID = value;
    }

}
