//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateOfIssue" type="{http://www.un.org/sanctions/1.0}DateSchemaType"/>
 *         &lt;element name="ReferenceValueSets" type="{http://www.un.org/sanctions/1.0}ReferenceValueSetsSchemaType"/>
 *         &lt;element name="Locations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Location" type="{http://www.un.org/sanctions/1.0}LocationSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IDRegDocuments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IDRegDocument" type="{http://www.un.org/sanctions/1.0}IDRegDocumentSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DistinctParties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DistinctParty" type="{http://www.un.org/sanctions/1.0}DistinctPartySchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProfileRelationships">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProfileRelationship" type="{http://www.un.org/sanctions/1.0}ProfileRelationshipSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SanctionsEntries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SanctionsEntry" type="{http://www.un.org/sanctions/1.0}SanctionsEntrySchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SanctionsEntryLinks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SanctionsEntryLink" type="{http://www.un.org/sanctions/1.0}SanctionsEntryLinkSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaBaseVersion" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dateOfIssue", "referenceValueSets", "locations", "idRegDocuments", "distinctParties", "profileRelationships", "sanctionsEntries", "sanctionsEntryLinks" })
@XmlRootElement(name = "Sanctions")
public class Sanctions {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DistinctParty" type="{http://www.un.org/sanctions/1.0}DistinctPartySchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "distinctParty" })
    public static class DistinctParties {

        @XmlElement(name = "DistinctParty")
        protected List<DistinctPartySchemaType> distinctParty;

        /**
         * Gets the value of the distinctParty property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the distinctParty property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getDistinctParty().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DistinctPartySchemaType }
         */
        public List<DistinctPartySchemaType> getDistinctParty() {
            if (distinctParty == null) {
                distinctParty = new ArrayList<DistinctPartySchemaType>();
            }
            return distinctParty;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IDRegDocument" type="{http://www.un.org/sanctions/1.0}IDRegDocumentSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "idRegDocument" })
    public static class IDRegDocuments {

        @XmlElement(name = "IDRegDocument")
        protected List<IDRegDocumentSchemaType> idRegDocument;

        /**
         * Gets the value of the idRegDocument property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the idRegDocument property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getIDRegDocument().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link IDRegDocumentSchemaType }
         */
        public List<IDRegDocumentSchemaType> getIDRegDocument() {
            if (idRegDocument == null) {
                idRegDocument = new ArrayList<IDRegDocumentSchemaType>();
            }
            return idRegDocument;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Location" type="{http://www.un.org/sanctions/1.0}LocationSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "location" })
    public static class Locations {

        @XmlElement(name = "Location")
        protected List<LocationSchemaType> location;

        /**
         * Gets the value of the location property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the location property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getLocation().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link LocationSchemaType }
         */
        public List<LocationSchemaType> getLocation() {
            if (location == null) {
                location = new ArrayList<LocationSchemaType>();
            }
            return location;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProfileRelationship" type="{http://www.un.org/sanctions/1.0}ProfileRelationshipSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "profileRelationship" })
    public static class ProfileRelationships {

        @XmlElement(name = "ProfileRelationship")
        protected List<ProfileRelationshipSchemaType> profileRelationship;

        /**
         * Gets the value of the profileRelationship property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the profileRelationship property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getProfileRelationship().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link ProfileRelationshipSchemaType }
         */
        public List<ProfileRelationshipSchemaType> getProfileRelationship() {
            if (profileRelationship == null) {
                profileRelationship = new ArrayList<ProfileRelationshipSchemaType>();
            }
            return profileRelationship;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SanctionsEntry" type="{http://www.un.org/sanctions/1.0}SanctionsEntrySchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "sanctionsEntry" })
    public static class SanctionsEntries {

        @XmlElement(name = "SanctionsEntry")
        protected List<SanctionsEntrySchemaType> sanctionsEntry;

        /**
         * Gets the value of the sanctionsEntry property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the sanctionsEntry property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getSanctionsEntry().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link SanctionsEntrySchemaType }
         */
        public List<SanctionsEntrySchemaType> getSanctionsEntry() {
            if (sanctionsEntry == null) {
                sanctionsEntry = new ArrayList<SanctionsEntrySchemaType>();
            }
            return sanctionsEntry;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SanctionsEntryLink" type="{http://www.un.org/sanctions/1.0}SanctionsEntryLinkSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "sanctionsEntryLink" })
    public static class SanctionsEntryLinks {

        @XmlElement(name = "SanctionsEntryLink")
        protected List<SanctionsEntryLinkSchemaType> sanctionsEntryLink;

        /**
         * Gets the value of the sanctionsEntryLink property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the sanctionsEntryLink property.
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getSanctionsEntryLink().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link SanctionsEntryLinkSchemaType }
         */
        public List<SanctionsEntryLinkSchemaType> getSanctionsEntryLink() {
            if (sanctionsEntryLink == null) {
                sanctionsEntryLink = new ArrayList<SanctionsEntryLinkSchemaType>();
            }
            return sanctionsEntryLink;
        }

    }

    @XmlElement(name = "DateOfIssue", required = true)
    protected DateSchemaType                 dateOfIssue;
    @XmlElement(name = "ReferenceValueSets", required = true)
    protected ReferenceValueSetsSchemaType   referenceValueSets;
    @XmlElement(name = "Locations", required = true)
    protected Sanctions.Locations            locations;
    @XmlElement(name = "IDRegDocuments", required = true)
    protected Sanctions.IDRegDocuments       idRegDocuments;

    @XmlElement(name = "DistinctParties", required = true)
    protected Sanctions.DistinctParties      distinctParties;

    @XmlElement(name = "ProfileRelationships", required = true)
    protected Sanctions.ProfileRelationships profileRelationships;

    @XmlElement(name = "SanctionsEntries", required = true)
    protected Sanctions.SanctionsEntries     sanctionsEntries;

    @XmlElement(name = "SanctionsEntryLinks", required = true)
    protected Sanctions.SanctionsEntryLinks  sanctionsEntryLinks;

    @XmlAttribute(name = "Version", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                     version;

    @XmlAttribute(name = "DeltaBaseVersion")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                     deltaBaseVersion;

    /**
     * Gets the value of the dateOfIssue property.
     *
     * @return possible object is {@link DateSchemaType }
     */
    public DateSchemaType getDateOfIssue() {
        return dateOfIssue;
    }

    /**
     * Gets the value of the deltaBaseVersion property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getDeltaBaseVersion() {
        return deltaBaseVersion;
    }

    /**
     * Gets the value of the distinctParties property.
     *
     * @return possible object is {@link Sanctions.DistinctParties }
     */
    public Sanctions.DistinctParties getDistinctParties() {
        return distinctParties;
    }

    /**
     * Gets the value of the idRegDocuments property.
     *
     * @return possible object is {@link Sanctions.IDRegDocuments }
     */
    public Sanctions.IDRegDocuments getIDRegDocuments() {
        return idRegDocuments;
    }

    /**
     * Gets the value of the locations property.
     *
     * @return possible object is {@link Sanctions.Locations }
     */
    public Sanctions.Locations getLocations() {
        return locations;
    }

    /**
     * Gets the value of the profileRelationships property.
     *
     * @return possible object is {@link Sanctions.ProfileRelationships }
     */
    public Sanctions.ProfileRelationships getProfileRelationships() {
        return profileRelationships;
    }

    /**
     * Gets the value of the referenceValueSets property.
     *
     * @return possible object is {@link ReferenceValueSetsSchemaType }
     */
    public ReferenceValueSetsSchemaType getReferenceValueSets() {
        return referenceValueSets;
    }

    /**
     * Gets the value of the sanctionsEntries property.
     *
     * @return possible object is {@link Sanctions.SanctionsEntries }
     */
    public Sanctions.SanctionsEntries getSanctionsEntries() {
        return sanctionsEntries;
    }

    /**
     * Gets the value of the sanctionsEntryLinks property.
     *
     * @return possible object is {@link Sanctions.SanctionsEntryLinks }
     */
    public Sanctions.SanctionsEntryLinks getSanctionsEntryLinks() {
        return sanctionsEntryLinks;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the dateOfIssue property.
     *
     * @param value
     *            allowed object is {@link DateSchemaType }
     */
    public void setDateOfIssue(final DateSchemaType value) {
        dateOfIssue = value;
    }

    /**
     * Sets the value of the deltaBaseVersion property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setDeltaBaseVersion(final BigInteger value) {
        deltaBaseVersion = value;
    }

    /**
     * Sets the value of the distinctParties property.
     *
     * @param value
     *            allowed object is {@link Sanctions.DistinctParties }
     */
    public void setDistinctParties(final Sanctions.DistinctParties value) {
        distinctParties = value;
    }

    /**
     * Sets the value of the idRegDocuments property.
     *
     * @param value
     *            allowed object is {@link Sanctions.IDRegDocuments }
     */
    public void setIDRegDocuments(final Sanctions.IDRegDocuments value) {
        idRegDocuments = value;
    }

    /**
     * Sets the value of the locations property.
     *
     * @param value
     *            allowed object is {@link Sanctions.Locations }
     */
    public void setLocations(final Sanctions.Locations value) {
        locations = value;
    }

    /**
     * Sets the value of the profileRelationships property.
     *
     * @param value
     *            allowed object is {@link Sanctions.ProfileRelationships }
     */
    public void setProfileRelationships(final Sanctions.ProfileRelationships value) {
        profileRelationships = value;
    }

    /**
     * Sets the value of the referenceValueSets property.
     *
     * @param value
     *            allowed object is {@link ReferenceValueSetsSchemaType }
     */
    public void setReferenceValueSets(final ReferenceValueSetsSchemaType value) {
        referenceValueSets = value;
    }

    /**
     * Sets the value of the sanctionsEntries property.
     *
     * @param value
     *            allowed object is {@link Sanctions.SanctionsEntries }
     */
    public void setSanctionsEntries(final Sanctions.SanctionsEntries value) {
        sanctionsEntries = value;
    }

    /**
     * Sets the value of the sanctionsEntryLinks property.
     *
     * @param value
     *            allowed object is {@link Sanctions.SanctionsEntryLinks }
     */
    public void setSanctionsEntryLinks(final Sanctions.SanctionsEntryLinks value) {
        sanctionsEntryLinks = value;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setVersion(final BigInteger value) {
        version = value;
    }

}
