//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for SanctionsEntrySchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SanctionsEntrySchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *         &lt;element name="LimitationsToListing" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntryEvent" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                   &lt;element name="Date" type="{http://www.un.org/sanctions/1.0}DateSchemaType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="EntryEventTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="LegalBasisID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SanctionsMeasure" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}DatePeriod"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="SanctionsTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SupportingInfo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Text" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="SupInfoTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}ProfileRelationshipReference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="ProfileID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="ListID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryProfileRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EntryDeltaFlag" type="{http://www.un.org/sanctions/1.0}EntryDeltaFlagSchemaType" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SanctionsEntrySchemaType", propOrder = { "comment", "limitationsToListing", "entryEvent", "sanctionsMeasure", "supportingInfo", "profileRelationshipReference" })
public class SanctionsEntrySchemaType {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *         &lt;element name="Date" type="{http://www.un.org/sanctions/1.0}DateSchemaType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="EntryEventTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="LegalBasisID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment", "date" })
    public static class EntryEvent {

        @XmlElement(name = "Comment")
        protected Comment               comment;
        @XmlElement(name = "Date", required = true)
        protected DateSchemaType        date;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            id;
        @XmlAttribute(name = "EntryEventTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            entryEventTypeID;
        @XmlAttribute(name = "LegalBasisID")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            legalBasisID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the comment property.
         *
         * @return possible object is {@link Comment }
         */
        public Comment getComment() {
            return comment;
        }

        /**
         * Gets the value of the date property.
         *
         * @return possible object is {@link DateSchemaType }
         */
        public DateSchemaType getDate() {
            return date;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the entryEventTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getEntryEventTypeID() {
            return entryEventTypeID;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Gets the value of the legalBasisID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getLegalBasisID() {
            return legalBasisID;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *            allowed object is {@link Comment }
         */
        public void setComment(final Comment value) {
            comment = value;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value
         *            allowed object is {@link DateSchemaType }
         */
        public void setDate(final DateSchemaType value) {
            date = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the entryEventTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setEntryEventTypeID(final BigInteger value) {
            entryEventTypeID = value;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setID(final BigInteger value) {
            id = value;
        }

        /**
         * Sets the value of the legalBasisID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setLegalBasisID(final BigInteger value) {
            legalBasisID = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class LimitationsToListing {

        @XmlValue
        protected String                value;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setValue(final String value) {
            this.value = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}DatePeriod"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="SanctionsTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment", "datePeriod" })
    public static class SanctionsMeasure {

        @XmlElement(name = "Comment")
        protected Comment               comment;
        @XmlElement(name = "DatePeriod", required = true)
        protected DatePeriod            datePeriod;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            id;
        @XmlAttribute(name = "SanctionsTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger            sanctionsTypeID;
        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the comment property.
         *
         * @return possible object is {@link Comment }
         */
        public Comment getComment() {
            return comment;
        }

        /**
         * Gets the value of the datePeriod property.
         *
         * @return possible object is {@link DatePeriod }
         */
        public DatePeriod getDatePeriod() {
            return datePeriod;
        }

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Gets the value of the sanctionsTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getSanctionsTypeID() {
            return sanctionsTypeID;
        }

        /**
         * Sets the value of the comment property.
         *
         * @param value
         *            allowed object is {@link Comment }
         */
        public void setComment(final Comment value) {
            comment = value;
        }

        /**
         * Sets the value of the datePeriod property.
         *
         * @param value
         *            allowed object is {@link DatePeriod }
         */
        public void setDatePeriod(final DatePeriod value) {
            datePeriod = value;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setID(final BigInteger value) {
            id = value;
        }

        /**
         * Sets the value of the sanctionsTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setSanctionsTypeID(final BigInteger value) {
            sanctionsTypeID = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Text" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.un.org/sanctions/1.0}DirectURL" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="SupInfoTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "text", "directURL" })
    public static class SupportingInfo {

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "value" })
        public static class Text {

            @XmlValue
            protected String                value;
            @XmlAttribute(name = "DeltaAction")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the deltaAction property.
             *
             * @return possible object is {@link DeltaActionSchemaType }
             */
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link String }
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the deltaAction property.
             *
             * @param value
             *            allowed object is {@link DeltaActionSchemaType }
             */
            public void setDeltaAction(final DeltaActionSchemaType value) {
                deltaAction = value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *            allowed object is {@link String }
             */
            public void setValue(final String value) {
                this.value = value;
            }

        }

        @XmlElement(name = "Text")
        protected SanctionsEntrySchemaType.SupportingInfo.Text text;
        @XmlElement(name = "DirectURL")
        protected DirectURL                                    directURL;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                   id;
        @XmlAttribute(name = "SupInfoTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger                                   supInfoTypeID;

        @XmlAttribute(name = "DeltaAction")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the deltaAction property.
         *
         * @return possible object is {@link DeltaActionSchemaType }
         */
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Gets the value of the directURL property.
         *
         * @return possible object is {@link DirectURL }
         */
        public DirectURL getDirectURL() {
            return directURL;
        }

        /**
         * Gets the value of the id property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getID() {
            return id;
        }

        /**
         * Gets the value of the supInfoTypeID property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getSupInfoTypeID() {
            return supInfoTypeID;
        }

        /**
         * Gets the value of the text property.
         *
         * @return possible object is {@link SanctionsEntrySchemaType.SupportingInfo.Text }
         */
        public SanctionsEntrySchemaType.SupportingInfo.Text getText() {
            return text;
        }

        /**
         * Sets the value of the deltaAction property.
         *
         * @param value
         *            allowed object is {@link DeltaActionSchemaType }
         */
        public void setDeltaAction(final DeltaActionSchemaType value) {
            deltaAction = value;
        }

        /**
         * Sets the value of the directURL property.
         *
         * @param value
         *            allowed object is {@link DirectURL }
         */
        public void setDirectURL(final DirectURL value) {
            directURL = value;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setID(final BigInteger value) {
            id = value;
        }

        /**
         * Sets the value of the supInfoTypeID property.
         *
         * @param value
         *            allowed object is {@link BigInteger }
         */
        public void setSupInfoTypeID(final BigInteger value) {
            supInfoTypeID = value;
        }

        /**
         * Sets the value of the text property.
         *
         * @param value
         *            allowed object is {@link SanctionsEntrySchemaType.SupportingInfo.Text }
         */
        public void setText(final SanctionsEntrySchemaType.SupportingInfo.Text value) {
            text = value;
        }

    }

    @XmlElement(name = "Comment")
    protected Comment                                         comment;
    @XmlElement(name = "LimitationsToListing")
    protected SanctionsEntrySchemaType.LimitationsToListing   limitationsToListing;
    @XmlElement(name = "EntryEvent", required = true)
    protected List<SanctionsEntrySchemaType.EntryEvent>       entryEvent;
    @XmlElement(name = "SanctionsMeasure", required = true)
    protected List<SanctionsEntrySchemaType.SanctionsMeasure> sanctionsMeasure;
    @XmlElement(name = "SupportingInfo")
    protected List<SanctionsEntrySchemaType.SupportingInfo>   supportingInfo;
    @XmlElement(name = "ProfileRelationshipReference")
    protected List<ProfileRelationshipReference>              profileRelationshipReference;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                                      id;
    @XmlAttribute(name = "ProfileID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger                                      profileID;

    @XmlAttribute(name = "ListID")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger listID;

    @XmlAttribute(name = "EntryProfileRef")
    protected String entryProfileRef;

    @XmlAttribute(name = "EntryDeltaFlag")
    protected EntryDeltaFlagSchemaType entryDeltaFlag;

    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is {@link Comment }
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the entryDeltaFlag property.
     *
     * @return possible object is {@link EntryDeltaFlagSchemaType }
     */
    public EntryDeltaFlagSchemaType getEntryDeltaFlag() {
        return entryDeltaFlag;
    }

    /**
     * Gets the value of the entryEvent property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the entryEvent property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getEntryEvent().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SanctionsEntrySchemaType.EntryEvent }
     */
    public List<SanctionsEntrySchemaType.EntryEvent> getEntryEvent() {
        if (entryEvent == null) {
            entryEvent = new ArrayList<SanctionsEntrySchemaType.EntryEvent>();
        }
        return entryEvent;
    }

    /**
     * Gets the value of the entryProfileRef property.
     *
     * @return possible object is {@link String }
     */
    public String getEntryProfileRef() {
        return entryProfileRef;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Gets the value of the limitationsToListing property.
     *
     * @return possible object is {@link SanctionsEntrySchemaType.LimitationsToListing }
     */
    public SanctionsEntrySchemaType.LimitationsToListing getLimitationsToListing() {
        return limitationsToListing;
    }

    /**
     * Gets the value of the listID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Gets the value of the profileID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getProfileID() {
        return profileID;
    }

    /**
     * Gets the value of the profileRelationshipReference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the profileRelationshipReference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getProfileRelationshipReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ProfileRelationshipReference }
     */
    public List<ProfileRelationshipReference> getProfileRelationshipReference() {
        if (profileRelationshipReference == null) {
            profileRelationshipReference = new ArrayList<ProfileRelationshipReference>();
        }
        return profileRelationshipReference;
    }

    /**
     * Gets the value of the sanctionsMeasure property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the sanctionsMeasure property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getSanctionsMeasure().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SanctionsEntrySchemaType.SanctionsMeasure }
     */
    public List<SanctionsEntrySchemaType.SanctionsMeasure> getSanctionsMeasure() {
        if (sanctionsMeasure == null) {
            sanctionsMeasure = new ArrayList<SanctionsEntrySchemaType.SanctionsMeasure>();
        }
        return sanctionsMeasure;
    }

    /**
     * Gets the value of the supportingInfo property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the supportingInfo property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getSupportingInfo().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SanctionsEntrySchemaType.SupportingInfo }
     */
    public List<SanctionsEntrySchemaType.SupportingInfo> getSupportingInfo() {
        if (supportingInfo == null) {
            supportingInfo = new ArrayList<SanctionsEntrySchemaType.SupportingInfo>();
        }
        return supportingInfo;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *            allowed object is {@link Comment }
     */
    public void setComment(final Comment value) {
        comment = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the entryDeltaFlag property.
     *
     * @param value
     *            allowed object is {@link EntryDeltaFlagSchemaType }
     */
    public void setEntryDeltaFlag(final EntryDeltaFlagSchemaType value) {
        entryDeltaFlag = value;
    }

    /**
     * Sets the value of the entryProfileRef property.
     *
     * @param value
     *            allowed object is {@link String }
     */
    public void setEntryProfileRef(final String value) {
        entryProfileRef = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

    /**
     * Sets the value of the limitationsToListing property.
     *
     * @param value
     *            allowed object is {@link SanctionsEntrySchemaType.LimitationsToListing }
     */
    public void setLimitationsToListing(final SanctionsEntrySchemaType.LimitationsToListing value) {
        limitationsToListing = value;
    }

    /**
     * Sets the value of the listID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setListID(final BigInteger value) {
        listID = value;
    }

    /**
     * Sets the value of the profileID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setProfileID(final BigInteger value) {
        profileID = value;
    }

}
