//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.15 at 02:50:54 PM MESZ
//

package at.jps.sanction.core.list.ofac.ASDM;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SanctionsEntryLinkSchemaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SanctionsEntryLinkSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.un.org/sanctions/1.0}Comment" minOccurs="0"/>
 *         &lt;element name="Date" type="{http://www.un.org/sanctions/1.0}DateSchemaType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryA-SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryB-SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryLinkTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{http://www.un.org/sanctions/1.0}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SanctionsEntryLinkSchemaType", propOrder = { "comment", "date" })
public class SanctionsEntryLinkSchemaType {

    @XmlElement(name = "Comment")
    protected Comment               comment;
    @XmlElement(name = "Date", required = true)
    protected DateSchemaType        date;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger            id;
    @XmlAttribute(name = "EntryA-SanctionsEntryID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger            entryASanctionsEntryID;
    @XmlAttribute(name = "EntryB-SanctionsEntryID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger            entryBSanctionsEntryID;
    @XmlAttribute(name = "EntryLinkTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger            entryLinkTypeID;
    @XmlAttribute(name = "DeltaAction")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is {@link Comment }
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is {@link DateSchemaType }
     */
    public DateSchemaType getDate() {
        return date;
    }

    /**
     * Gets the value of the deltaAction property.
     *
     * @return possible object is {@link DeltaActionSchemaType }
     */
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Gets the value of the entryASanctionsEntryID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getEntryASanctionsEntryID() {
        return entryASanctionsEntryID;
    }

    /**
     * Gets the value of the entryBSanctionsEntryID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getEntryBSanctionsEntryID() {
        return entryBSanctionsEntryID;
    }

    /**
     * Gets the value of the entryLinkTypeID property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getEntryLinkTypeID() {
        return entryLinkTypeID;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value
     *            allowed object is {@link Comment }
     */
    public void setComment(final Comment value) {
        comment = value;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *            allowed object is {@link DateSchemaType }
     */
    public void setDate(final DateSchemaType value) {
        date = value;
    }

    /**
     * Sets the value of the deltaAction property.
     *
     * @param value
     *            allowed object is {@link DeltaActionSchemaType }
     */
    public void setDeltaAction(final DeltaActionSchemaType value) {
        deltaAction = value;
    }

    /**
     * Sets the value of the entryASanctionsEntryID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setEntryASanctionsEntryID(final BigInteger value) {
        entryASanctionsEntryID = value;
    }

    /**
     * Sets the value of the entryBSanctionsEntryID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setEntryBSanctionsEntryID(final BigInteger value) {
        entryBSanctionsEntryID = value;
    }

    /**
     * Sets the value of the entryLinkTypeID property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setEntryLinkTypeID(final BigInteger value) {
        entryLinkTypeID = value;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     */
    public void setID(final BigInteger value) {
        id = value;
    }

}
