//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 09:15:55 PM CET
//

package at.jps.sanction.core.list.dj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DateValue" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Dnotes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DateType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "date" })
@XmlRootElement(name = "DateDetails")
public class DateDetails {

    @XmlElement(name = "Date")
    protected List<DateDetails.Date> date;

    /**
     * Gets the value of the date property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the date property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDate().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DateDetails.Date }
     */
    public List<DateDetails.Date> getDate() {
        if (date == null) {
            date = new ArrayList<DateDetails.Date>();
        }
        return this.date;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DateValue" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Dnotes" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="DateType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "dateValue" })
    public static class Date {

        @XmlElement(name = "DateValue")
        protected List<DateDetails.Date.DateValue> dateValue;
        @XmlAttribute(name = "DateType")
        protected String                           dateType;

        /**
         * Gets the value of the dateValue property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the dateValue property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getDateValue().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link DateDetails.Date.DateValue }
         */
        public List<DateDetails.Date.DateValue> getDateValue() {
            if (dateValue == null) {
                dateValue = new ArrayList<DateDetails.Date.DateValue>();
            }
            return this.dateValue;
        }

        /**
         * Gets the value of the dateType property.
         * 
         * @return possible object is {@link String }
         */
        public String getDateType() {
            return dateType;
        }

        /**
         * Sets the value of the dateType property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setDateType(String value) {
            this.dateType = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Month" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Year" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Day" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Dnotes" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DateValue {

            @XmlAttribute(name = "Month")
            protected String month;
            @XmlAttribute(name = "Year")
            protected String year;
            @XmlAttribute(name = "Day")
            protected String day;
            @XmlAttribute(name = "Dnotes")
            protected String dnotes;

            /**
             * Gets the value of the month property.
             * 
             * @return possible object is {@link String }
             */
            public String getMonth() {
                return month;
            }

            /**
             * Sets the value of the month property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setMonth(String value) {
                this.month = value;
            }

            /**
             * Gets the value of the year property.
             * 
             * @return possible object is {@link String }
             */
            public String getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setYear(String value) {
                this.year = value;
            }

            /**
             * Gets the value of the day property.
             * 
             * @return possible object is {@link String }
             */
            public String getDay() {
                return day;
            }

            /**
             * Sets the value of the day property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setDay(String value) {
                this.day = value;
            }

            /**
             * Gets the value of the dnotes property.
             * 
             * @return possible object is {@link String }
             */
            public String getDnotes() {
                return dnotes;
            }

            /**
             * Sets the value of the dnotes property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setDnotes(String value) {
                this.dnotes = value;
            }

        }

    }

}
