//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 09:15:55 PM CET
//

package at.jps.sanction.core.list.dj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Description1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Description2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Description3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "description" })
@XmlRootElement(name = "Descriptions")
public class Descriptions {

    @XmlElement(name = "Description")
    protected List<Descriptions.Description> description;

    /**
     * Gets the value of the description property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the description property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDescription().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Descriptions.Description }
     */
    public List<Descriptions.Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Descriptions.Description>();
        }
        return description;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Description1" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Description2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Description3" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Description {

        @XmlAttribute(name = "Description1")
        protected String description1;
        @XmlAttribute(name = "Description2")
        protected String description2;
        @XmlAttribute(name = "Description3")
        protected String description3;

        /**
         * Gets the value of the description1 property.
         *
         * @return possible object is {@link String }
         */
        public String getDescription1() {
            return description1;
        }

        /**
         * Sets the value of the description1 property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setDescription1(final String value) {
            description1 = value;
        }

        /**
         * Gets the value of the description2 property.
         *
         * @return possible object is {@link String }
         */
        public String getDescription2() {
            return description2;
        }

        /**
         * Sets the value of the description2 property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setDescription2(final String value) {
            description2 = value;
        }

        /**
         * Gets the value of the description3 property.
         *
         * @return possible object is {@link String }
         */
        public String getDescription3() {
            return description3;
        }

        /**
         * Sets the value of the description3 property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setDescription3(final String value) {
            description3 = value;
        }

    }

}
