//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 09:15:55 PM CET
//

package at.jps.sanction.core.list.dj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NameValue" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TitleHonorific" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="MaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SingleStringName" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="OriginalScriptName" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="NameType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name" })
@XmlRootElement(name = "NameDetails")
public class NameDetails {

    @XmlElement(name = "Name")
    protected List<NameDetails.Name> name;

    /**
     * Gets the value of the name property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the name property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getName().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link NameDetails.Name }
     */
    public List<NameDetails.Name> getName() {
        if (name == null) {
            name = new ArrayList<NameDetails.Name>();
        }
        return this.name;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NameValue" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TitleHonorific" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="MaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SingleStringName" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="OriginalScriptName" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="NameType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "nameValue" })
    public static class Name {

        @XmlElement(name = "NameValue")
        protected List<NameDetails.Name.NameValue> nameValue;
        @XmlAttribute(name = "NameType")
        protected String                           nameType;

        /**
         * Gets the value of the nameValue property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there
         * is not a <CODE>set</CODE> method for the nameValue property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getNameValue().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link NameDetails.Name.NameValue }
         */
        public List<NameDetails.Name.NameValue> getNameValue() {
            if (nameValue == null) {
                nameValue = new ArrayList<NameDetails.Name.NameValue>();
            }
            return this.nameValue;
        }

        /**
         * Gets the value of the nameType property.
         * 
         * @return possible object is {@link String }
         */
        public String getNameType() {
            return nameType;
        }

        /**
         * Sets the value of the nameType property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setNameType(String value) {
            this.nameType = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TitleHonorific" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="MaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SingleStringName" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="OriginalScriptName" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "titleHonorific", "maidenName", "firstName", "middleName", "surname", "suffix", "entityName", "singleStringName", "originalScriptName" })
        public static class NameValue {

            @XmlElement(name = "TitleHonorific")
            protected String                                              titleHonorific;
            @XmlElement(name = "MaidenName")
            protected String                                              maidenName;
            @XmlElement(name = "FirstName")
            protected String                                              firstName;
            @XmlElement(name = "MiddleName")
            protected String                                              middleName;
            @XmlElement(name = "Surname")
            protected String                                              surname;
            @XmlElement(name = "Suffix")
            protected String                                              suffix;
            @XmlElement(name = "EntityName")
            protected String                                              entityName;
            @XmlElement(name = "SingleStringName", nillable = true)
            protected List<NameDetails.Name.NameValue.SingleStringName>   singleStringName;
            @XmlElement(name = "OriginalScriptName", nillable = true)
            protected List<NameDetails.Name.NameValue.OriginalScriptName> originalScriptName;

            /**
             * Gets the value of the titleHonorific property.
             * 
             * @return possible object is {@link String }
             */
            public String getTitleHonorific() {
                return titleHonorific;
            }

            /**
             * Sets the value of the titleHonorific property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setTitleHonorific(String value) {
                this.titleHonorific = value;
            }

            /**
             * Gets the value of the maidenName property.
             * 
             * @return possible object is {@link String }
             */
            public String getMaidenName() {
                return maidenName;
            }

            /**
             * Sets the value of the maidenName property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setMaidenName(String value) {
                this.maidenName = value;
            }

            /**
             * Gets the value of the firstName property.
             * 
             * @return possible object is {@link String }
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the middleName property.
             * 
             * @return possible object is {@link String }
             */
            public String getMiddleName() {
                return middleName;
            }

            /**
             * Sets the value of the middleName property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setMiddleName(String value) {
                this.middleName = value;
            }

            /**
             * Gets the value of the surname property.
             * 
             * @return possible object is {@link String }
             */
            public String getSurname() {
                return surname;
            }

            /**
             * Sets the value of the surname property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setSurname(String value) {
                this.surname = value;
            }

            /**
             * Gets the value of the suffix property.
             * 
             * @return possible object is {@link String }
             */
            public String getSuffix() {
                return suffix;
            }

            /**
             * Sets the value of the suffix property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setSuffix(String value) {
                this.suffix = value;
            }

            /**
             * Gets the value of the entityName property.
             * 
             * @return possible object is {@link String }
             */
            public String getEntityName() {
                return entityName;
            }

            /**
             * Sets the value of the entityName property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setEntityName(String value) {
                this.entityName = value;
            }

            /**
             * Gets the value of the singleStringName property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why
             * there is not a <CODE>set</CODE> method for the singleStringName property.
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getSingleStringName().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link NameDetails.Name.NameValue.SingleStringName }
             */
            public List<NameDetails.Name.NameValue.SingleStringName> getSingleStringName() {
                if (singleStringName == null) {
                    singleStringName = new ArrayList<NameDetails.Name.NameValue.SingleStringName>();
                }
                return this.singleStringName;
            }

            /**
             * Gets the value of the originalScriptName property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why
             * there is not a <CODE>set</CODE> method for the originalScriptName property.
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getOriginalScriptName().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link NameDetails.Name.NameValue.OriginalScriptName }
             */
            public List<NameDetails.Name.NameValue.OriginalScriptName> getOriginalScriptName() {
                if (originalScriptName == null) {
                    originalScriptName = new ArrayList<NameDetails.Name.NameValue.OriginalScriptName>();
                }
                return this.originalScriptName;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class OriginalScriptName {

                @XmlValue
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return possible object is {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "value" })
            public static class SingleStringName {

                @XmlValue
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return possible object is {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *            allowed object is {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }

}
