//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 09:15:55 PM CET
//

package at.jps.sanction.core.list.dj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}NameDetails"/>
 *         &lt;element ref="{}Descriptions"/>
 *         &lt;element ref="{}DateDetails"/>
 *         &lt;element ref="{}SanctionsReferences"/>
 *         &lt;element ref="{}CountryDetails"/>
 *         &lt;element ref="{}IDNumberTypes"/>
 *         &lt;element ref="{}SourceDescription"/>
 *         &lt;element ref="{}Associate"/>
 *         &lt;element ref="{}PFA"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "nameDetailsOrDescriptionsOrDateDetails" })
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

    @XmlElements({ @XmlElement(name = "NameDetails", type = NameDetails.class), @XmlElement(name = "Descriptions", type = Descriptions.class),
            @XmlElement(name = "DateDetails", type = DateDetails.class), @XmlElement(name = "SanctionsReferences", type = SanctionsReferences.class),
            @XmlElement(name = "CountryDetails", type = CountryDetails.class), @XmlElement(name = "IDNumberTypes", type = IDNumberTypes.class),
            @XmlElement(name = "SourceDescription", type = SourceDescription.class), @XmlElement(name = "Associate", type = Associate.class), @XmlElement(name = "PFA", type = PFA.class) })
    protected List<Object> nameDetailsOrDescriptionsOrDateDetails;

    /**
     * Gets the value of the nameDetailsOrDescriptionsOrDateDetails property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the nameDetailsOrDescriptionsOrDateDetails property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getNameDetailsOrDescriptionsOrDateDetails().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link NameDetails } {@link Descriptions } {@link DateDetails } {@link SanctionsReferences } {@link CountryDetails }
     * {@link IDNumberTypes } {@link SourceDescription } {@link Associate } {@link PFA }
     */
    public List<Object> getNameDetailsOrDescriptionsOrDateDetails() {
        if (nameDetailsOrDescriptionsOrDateDetails == null) {
            nameDetailsOrDescriptionsOrDateDetails = new ArrayList<Object>();
        }
        return nameDetailsOrDescriptionsOrDateDetails;
    }

}
