/*******************************************************************************
 * Copyright (c) 2015 Jim Fandango (The Last Guy Coding) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 * A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.25 at 10:47:25 AM MESZ
//

package at.jps.sanction.core.list.dj;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the at.jps.aml.xml.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.jps.aml.xml.model
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountryDetails }
     */
    public CountryDetails createCountryDetails() {
        return new CountryDetails();
    }

    /**
     * Create an instance of {@link CountryDetails.Country }
     */
    public CountryDetails.Country createCountryDetailsCountry() {
        return new CountryDetails.Country();
    }

    /**
     * Create an instance of {@link CountryDetails.Country.CountryValue }
     */
    public CountryDetails.Country.CountryValue createCountryDetailsCountryCountryValue() {
        return new CountryDetails.Country.CountryValue();
    }

    /**
     * Create an instance of {@link DateDetails }
     */
    public DateDetails createDateDetails() {
        return new DateDetails();
    }

    /**
     * Create an instance of {@link DateDetails.Date }
     */
    public DateDetails.Date createDateDetailsDate() {
        return new DateDetails.Date();
    }

    /**
     * Create an instance of {@link DateDetails.Date.DateValue }
     */
    public DateDetails.Date.DateValue createDateDetailsDateDateValue() {
        return new DateDetails.Date.DateValue();
    }

    /**
     * Create an instance of {@link Descriptions }
     */
    public Descriptions createDescriptions() {
        return new Descriptions();
    }

    /**
     * Create an instance of {@link Descriptions.Description }
     */
    public Descriptions.Description createDescriptionsDescription() {
        return new Descriptions.Description();
    }

    /**
     * Create an instance of {@link IDNumberTypes }
     */
    public IDNumberTypes createIDNumberTypes() {
        return new IDNumberTypes();
    }

    /**
     * Create an instance of {@link IDNumberTypes.ID }
     */
    public IDNumberTypes.ID createIDNumberTypesID() {
        return new IDNumberTypes.ID();
    }

    /**
     * Create an instance of {@link IDNumberTypes.ID.IDValue }
     */
    public IDNumberTypes.ID.IDValue createIDNumberTypesIDIDValue() {
        return new IDNumberTypes.ID.IDValue();
    }

    /**
     * Create an instance of {@link NameDetails }
     */
    public NameDetails createNameDetails() {
        return new NameDetails();
    }

    /**
     * Create an instance of {@link NameDetails.Name }
     */
    public NameDetails.Name createNameDetailsName() {
        return new NameDetails.Name();
    }

    /**
     * Create an instance of {@link NameDetails.Name.NameValue }
     */
    public NameDetails.Name.NameValue createNameDetailsNameNameValue() {
        return new NameDetails.Name.NameValue();
    }

    /**
     * Create an instance of {@link NameDetails.Name.NameValue.OriginalScriptName }
     */
    public NameDetails.Name.NameValue.OriginalScriptName createNameDetailsNameNameValueOriginalScriptName() {
        return new NameDetails.Name.NameValue.OriginalScriptName();
    }

    /**
     * Create an instance of {@link NameDetails.Name.NameValue.SingleStringName }
     */
    public NameDetails.Name.NameValue.SingleStringName createNameDetailsNameNameValueSingleStringName() {
        return new NameDetails.Name.NameValue.SingleStringName();
    }

    /**
     * Create an instance of {@link NewDataSet }
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link PFA }
     */
    public PFA createPFA() {
        return new PFA();
    }

    /**
     * Create an instance of {@link PFA.CountryList }
     */
    public PFA.CountryList createPFACountryList() {
        return new PFA.CountryList();
    }

    /**
     * Create an instance of {@link PFA.CountryList.CountryName }
     */
    public PFA.CountryList.CountryName createPFACountryListCountryName() {
        return new PFA.CountryList.CountryName();
    }

    /**
     * Create an instance of {@link PFA.DateTypeList }
     */
    public PFA.DateTypeList createPFADateTypeList() {
        return new PFA.DateTypeList();
    }

    /**
     * Create an instance of {@link PFA.DateTypeList.DateType }
     */
    public PFA.DateTypeList.DateType createPFADateTypeListDateType() {
        return new PFA.DateTypeList.DateType();
    }

    /**
     * Create an instance of {@link PFA.Description1List }
     */
    public PFA.Description1List createPFADescription1List() {
        return new PFA.Description1List();
    }

    /**
     * Create an instance of {@link PFA.Description1List.Description1Name }
     */
    public PFA.Description1List.Description1Name createPFADescription1ListDescription1Name() {
        return new PFA.Description1List.Description1Name();
    }

    /**
     * Create an instance of {@link PFA.Description2List }
     */
    public PFA.Description2List createPFADescription2List() {
        return new PFA.Description2List();
    }

    /**
     * Create an instance of {@link PFA.Description2List.Description2Name }
     */
    public PFA.Description2List.Description2Name createPFADescription2ListDescription2Name() {
        return new PFA.Description2List.Description2Name();
    }

    /**
     * Create an instance of {@link PFA.Description3List }
     */
    public PFA.Description3List createPFADescription3List() {
        return new PFA.Description3List();
    }

    /**
     * Create an instance of {@link PFA.Description3List.Description3Name }
     */
    public PFA.Description3List.Description3Name createPFADescription3ListDescription3Name() {
        return new PFA.Description3List.Description3Name();
    }

    /**
     * Create an instance of {@link PFA.NameTypeList }
     */
    public PFA.NameTypeList createPFANameTypeList() {
        return new PFA.NameTypeList();
    }

    /**
     * Create an instance of {@link PFA.NameTypeList.NameType }
     */
    public PFA.NameTypeList.NameType createPFANameTypeListNameType() {
        return new PFA.NameTypeList.NameType();
    }

    /**
     * Create an instance of {@link PFA.OccupationList }
     */
    public PFA.OccupationList createPFAOccupationList() {
        return new PFA.OccupationList();
    }

    /**
     * Create an instance of {@link PFA.OccupationList.Occupation }
     */
    public PFA.OccupationList.Occupation createPFAOccupationListOccupation() {
        return new PFA.OccupationList.Occupation();
    }

    /**
     * Create an instance of {@link PFA.Records }
     */
    public PFA.Records createPFARecords() {
        return new PFA.Records();
    }

    /**
     * Create an instance of {@link PFA.Records.Entity }
     */
    public PFA.Records.Entity createPFARecordsEntity() {
        return new PFA.Records.Entity();
    }

    /**
     * Create an instance of {@link PFA.Records.Entity.CompanyDetails }
     */
    public PFA.Records.Entity.CompanyDetails createPFARecordsEntityCompanyDetails() {
        return new PFA.Records.Entity.CompanyDetails();
    }

    /**
     * Create an instance of {@link PFA.Records.Entity.VesselDetails }
     */
    public PFA.Records.Entity.VesselDetails createPFARecordsEntityVesselDetails() {
        return new PFA.Records.Entity.VesselDetails();
    }

    /**
     * Create an instance of {@link PFA.Records.Person }
     */
    public PFA.Records.Person createPFARecordsPerson() {
        return new PFA.Records.Person();
    }

    /**
     * Create an instance of {@link PFA.Records.Person.Address }
     */
    public PFA.Records.Person.Address createPFARecordsPersonAddress() {
        return new PFA.Records.Person.Address();
    }

    /**
     * Create an instance of {@link PFA.Records.Person.BirthPlace }
     */
    public PFA.Records.Person.BirthPlace createPFARecordsPersonBirthPlace() {
        return new PFA.Records.Person.BirthPlace();
    }

    /**
     * Create an instance of {@link PFA.Records.Person.BirthPlace.Place }
     */
    public PFA.Records.Person.BirthPlace.Place createPFARecordsPersonBirthPlacePlace() {
        return new PFA.Records.Person.BirthPlace.Place();
    }

    /**
     * Create an instance of {@link PFA.RelationshipList }
     */
    public PFA.RelationshipList createPFARelationshipList() {
        return new PFA.RelationshipList();
    }

    /**
     * Create an instance of {@link PFA.RelationshipList.Relationship }
     */
    public PFA.RelationshipList.Relationship createPFARelationshipListRelationship() {
        return new PFA.RelationshipList.Relationship();
    }

    /**
     * Create an instance of {@link PFA.RoleTypeList }
     */
    public PFA.RoleTypeList createPFARoleTypeList() {
        return new PFA.RoleTypeList();
    }

    /**
     * Create an instance of {@link PFA.RoleTypeList.RoleType }
     */
    public PFA.RoleTypeList.RoleType createPFARoleTypeListRoleType() {
        return new PFA.RoleTypeList.RoleType();
    }

    /**
     * Create an instance of {@link PFA.SanctionsReferencesList }
     */
    public PFA.SanctionsReferencesList createPFASanctionsReferencesList() {
        return new PFA.SanctionsReferencesList();
    }

    /**
     * Create an instance of {@link PFA.SanctionsReferencesList.ReferenceName }
     */
    public PFA.SanctionsReferencesList.ReferenceName createPFASanctionsReferencesListReferenceName() {
        return new PFA.SanctionsReferencesList.ReferenceName();
    }

    /**
     * Create an instance of {@link SanctionsReferences }
     */
    public SanctionsReferences createSanctionsReferences() {
        return new SanctionsReferences();
    }

    /**
     * Create an instance of {@link SanctionsReferences.Reference }
     */
    public SanctionsReferences.Reference createSanctionsReferencesReference() {
        return new SanctionsReferences.Reference();
    }

    /**
     * Create an instance of {@link SourceDescription }
     */
    public SourceDescription createSourceDescription() {
        return new SourceDescription();
    }

    /**
     * Create an instance of {@link SourceDescription.Source }
     */
    public SourceDescription.Source createSourceDescriptionSource() {
        return new SourceDescription.Source();
    }

}
