/*******************************************************************************
 * Copyright (c) 2015 Jim Fandango (The Last Guy Coding) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 * A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.25 at 10:47:25 AM MESZ
//

package at.jps.sanction.core.list.dj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reference" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="SinceDay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SinceMonth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SinceYear" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "reference" })
@XmlRootElement(name = "SanctionsReferences")
public class SanctionsReferences {

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="SinceDay" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SinceMonth" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SinceYear" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Reference {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "SinceDay")
        protected String sinceDay;
        @XmlAttribute(name = "SinceMonth")
        protected String sinceMonth;
        @XmlAttribute(name = "SinceYear")
        protected String sinceYear;

        /**
         * Gets the value of the sinceDay property.
         *
         * @return possible object is {@link String }
         */
        public String getSinceDay() {
            return sinceDay;
        }

        /**
         * Gets the value of the sinceMonth property.
         *
         * @return possible object is {@link String }
         */
        public String getSinceMonth() {
            return sinceMonth;
        }

        /**
         * Gets the value of the sinceYear property.
         *
         * @return possible object is {@link String }
         */
        public String getSinceYear() {
            return sinceYear;
        }

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the sinceDay property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setSinceDay(final String value) {
            sinceDay = value;
        }

        /**
         * Sets the value of the sinceMonth property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setSinceMonth(final String value) {
            sinceMonth = value;
        }

        /**
         * Sets the value of the sinceYear property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setSinceYear(final String value) {
            sinceYear = value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setValue(final String value) {
            this.value = value;
        }

    }

    @XmlElement(name = "Reference", nillable = true)
    protected List<SanctionsReferences.Reference> reference;

    /**
     * Gets the value of the reference property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is
     * not a <CODE>set</CODE> method for the reference property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getReference().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SanctionsReferences.Reference }
     */
    public List<SanctionsReferences.Reference> getReference() {
        if (reference == null) {
            reference = new ArrayList<SanctionsReferences.Reference>();
        }
        return reference;
    }

}
